#!/bin/bash
# -*- Mode: sh; coding: utf-8; indent-tabs-mode: nil; tab-width: 4 -*-
#
# Authors:
#   Sam Hewitt <hewittsamuel@gmail.com>
#
# Description:
#   An installation bash script for Moka GTK Theme
#
# Legal Stuff:
#
# This file is part of the Moka GTK Theme and is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; version 3.
#
# This file is part of the Moka GTK Theme and is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, see <https://www.gnu.org/licenses/gpl-3.0.txt>

clear
echo '#-----------------------------------------#'
echo '#     Moka GTK Theme Install Script      #'
echo '#-----------------------------------------#'

function continue {
echo
read -p "Do you want to continue? (Y)es, (N)o : " INPUT
case $INPUT in
	[Yy]* ) ;;
    [Nn]* ) exit 99;;
    * ) echo; echo "Uh oh, invalid response. Please retry."; continue;;
esac
}

ROOT_UID=0
if [ "$UID" -ne "$ROOT_UID" ]; then
	echo
	echo "Moka GTK Theme will be installed in '$HOME/.themes'."
	echo "To make them available to all users, run this script as root."
	continue
else
	echo
	echo "Moka GTK Theme will be installed in '/usr/share/themes'"
	echo "It will be available to all users."
	continue
fi
echo

if [ "$UID" -eq "$ROOT_UID" ]; then
	if [ -d /usr/share/themes/Moka ]; then
		echo
		read -p "Found an existing installation. Remove it? (Y)es, (N)o : " INPUT
		case $INPUT in
			[Yy]* ) rm -Rf /usr/share/themes/Moka 2>/dev/null;;
			[Nn]* );;
		    * ) ;;
		esac
	fi
	cp -R ./Moka/ /usr/share/themes/
	install_dir=/usr/share/themes/
elif [ "$UID" -ne "$ROOT_UID" ]; then
	if [ -d $HOME/.themes/Moka ]; then
		echo
		read -p "Found an existing installation. Remove it? (Y)es, (N)o : " INPUT
		case $INPUT in
			[Yy]* ) rm -Rf "$HOME/.themes/Moka" 2>/dev/null;;
			[Nn]* );;
		    * ) ;;
		esac
	fi
	cp -R ./Moka/ "$HOME/.themes/"
	install_dir="$HOME/.themes/"
fi

function settheme {
echo "Setting Moka as desktop GTK theme..."
gsettings set org.gnome.desktop.interface gtk-theme "Moka"
gsettings set org.gnome.desktop.wm.preferences theme "Moka"
echo "Done."
}

function set {
echo "Installation complete!"
read -p "Do you want to set Moka as desktop icon set? (Y)es, (N)o : " INPUT
case $INPUT in
	[Yy]* ) settheme;;
    [Nn]* );;
    * ) echo; echo "Uh oh, invalid response. Please retry."; set;;
esac
}

echo ''
set
echo "Exiting"
exit 0