#!/bin/bash
# -*- Mode: sh; coding: utf-8; indent-tabs-mode: nil; tab-width: 4 -*-
#
# Authors:
#   Sam Hewitt <hewittsamuel@gmail.com>
#
# Description:
#   An uninstallation bash script for Moka GTK Theme
#
# Legal Stuff:
#
# This file is part of the Moka GTK Theme and is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; version 3.
#
# This file is part of the Moka GTK Theme and is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, see <https://www.gnu.org/licenses/gpl-3.0.txt>

clear
echo '#------------------------------------------#'
echo '#     Moka GTK Theme Uninstall Script      #'
echo '#------------------------------------------#'

function continue {
echo
read -p "Do you want to continue? (Y)es, (N)o : " INPUT
case $INPUT in
	[Yy]* ) ;;
    [Nn]* ) exit 99;;
    * ) echo; echo "Uh oh, invalid response. Please retry."; continue;;
esac
}

ROOT_UID=0
if [ "$UID" -ne "$ROOT_UID" ]; then
	echo
	echo "Moka GTK Theme will be removed in '$HOME/.themes'."
	echo "To remove them from the system-wide themes, run this script as root."
	continue
else
	echo
	echo "Moka GTK Theme will be removed from '/usr/share/themes'"
	echo "It will be no longer be available to all users."
	continue
fi
echo

if [ "$UID" -eq "$ROOT_UID" ]; then
	rm -Rf /usr/share/themes/Moka 2>/dev/null
else
	rm -Rf $HOME/.themes/Moka 2>/dev/null
fi

echo
echo "Uninstallation complete."
# Reset icon theme via GSettings
echo "Resetting desktop GTK theme..."
gsettings reset org.gnome.desktop.interface gtk-theme
gsettings reset org.gnome.desktop.wm.preferences theme
echo "Done."
echo "Exiting"
exit 0